name: elasticmapper_scripts
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - matplotlib
  - notebook
  - numpy
  - obspy
  - pip
  - pygmt
  - scipy
  - pip:
    - git+https://github.com/adjtomo/pysep.git@devel
